version: "3.9"
services:
  mysql-sakila:
    image: mysql:8.3
    container_name: mysql-sakila
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      MYSQL_USER: sakila
      MYSQL_PASSWORD: sakila
    ports:
      - "3307:3306"
    volumes:
      - ./src/main/sql/sakila-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/sql/sakila-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-hsakila", "-psakila" ]
      interval: 10s
      timeout: 10s
      retries: 10

  mongo:
    image: mongo:7
    container_name: mcp-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  mongo-init:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mcp-mongo-init
    depends_on:
      - mongo
    volumes:
      - ./src/main/mongo/init.sh:/init.sh
    command: [ "bash", "/init.sh" ]

volumes:
  mongo_data: