
version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mcp-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  mongo-init:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mcp-mongo-init
    depends_on:
      - mongo
    volumes:
      - ./src/main/mongo/data:/data
    command: [ "bash", "/data/init.sh" ]

volumes:
  mongo_data:
