spring:
  application:
    name: melian-mcp-server

  ai:
    mcp:
      server:
        enabled: true
        stdio: true
        tcp: true
        type: SYNC
        name: melian-movie-server
        version: 1.0.0
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        host: 0.0.0.0
        port: 3001  # ✅ Puerto separado para MCP

  main:
    web-application-type: servlet
    banner-mode: off

  server:
    port: 3000        # ✅ Puerto para Spring Boot web
    address: 0.0.0.0

  datasource:
    url: jdbc:mysql://mysql-sakila:3306/sakila
    username: sakila
    password: sakila
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    mongodb:
      uri: mongodb://root:example@mongo:27017/melian_movies?authSource=admin

tmdb:
  api-url: https://api.themoviedb.org/3
  access-token: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkYzEzOThhZDciMTY4ZjM2ZGJkMGIzYTZmYTYzOThhYSIsIm5iZiI6MTc0OTkzNDEyNi4xNDgsInN1YiI6IjY4NGRlMDJlYzgzZWJlNzgxOWJiNGU1YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.oI0cWBV3BQmfGNqjh27YLAqNuZK2gIQW-wkYeamNv5Y"

logging:
  level:
    root: INFO
    org.shark.melian: DEBUG
    org.mongodb.driver: WARN
