spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:example@localhost:27017/melian_movies?authSource=admin}


# Pued es mantener la configuración anterior si otros componentes la usan
mongodb:
  uri: mongodb://localhost:27017
  database: melian_movies

# src/main/resources/application.yml

melian:
  mcp:
    server:
      port: 3000
      host: localhost
      http:
        enabled: true
  tmdb:
    api-url: https://api.themoviedb.org/3
    access-token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkYzEzOThhZDciMTY4ZjM2ZGJkMGIzYTZmYTYzOThhYSIsIm5iZiI6MTc0OTkzNDEyNi4xNDgsInN1YiI6IjY4NGRlMDJlYzgzZWJlNzgxOWJiNGU1YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.oI0cWBV3BQmfGNqjh27YLAqNuZK2gIQW-wkYeamNv5Y
  imdb:
    api-url: https://api.themoviedb.org/3
    access-token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkYzEzOThhZDciMTY4ZjM2ZGJkMGIzYTZmYTYzOThhYSIsIm5iZiI6MTc0OTkzNDEyNi4xNDgsInN1YiI6IjY4NGRlMDJlYzgzZWJlNzgxOWJiNGU1YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.oI0cWBV3BQmfGNqjh27YLAqNuZK2gIQW-wkYeamNv5Y
  search:
    locale: en


logging:
  level:
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.shark.melian.repository.CustomMovieDocumentRepositoryImpl: DEBUG


