spring:
  application:
    name: melian-mcp-server

  ai:
    mcp:
      server:
        enabled: true
        stdio: true
        type: SYNC
        name: melian-movie-server
        version: 1.0.0
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true

  main:
    web-application-type: none
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3307/sakila
    username: sakila
    password: sakila
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    mongodb:
      host: localhost
      port: 27017
      database: melian_movies
      username: root
      password: example

tmdb:
  api-url: https://api.themoviedb.org/3
  access-token: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkYzEzOThhZDciMTY4ZjM2ZGJkMGIzYTZmYTYzOThhYSIsIm5iZiI6MTc0OTkzNDEyNi4xNDgsInN1YiI6IjY4NGRlMDJlYzgzZWJlNzgxOWJiNGU1YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.oI0cWBV3BQmfGNqjh27YLAqNuZK2gIQW-wkYeamNv5Y"

melian:
  filesystem:
    scan:
      directory: "/tmp/melian-scan"

logging:
  pattern:
    console: ""
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.shark.melian: DEBUG
    org.springframework.context: DEBUG
