spring:
  application:
    name: melian-mcp-server

  ai:
    mcp:
      server:
        enabled: true
        stdio: true
        type: SYNC
        name: melian-movie-server
        version: 1.0.0
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
  main:
    web-application-type: none
    banner-mode: off

  # Database configuration
  datasource:
    # H2 for testing or MySQL for production
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  data:
    mongodb:
      # MongoDB configuration
      host: localhost
      port: 27017
      database: melian_movies
      # username: admin
      # password: admin

# TMDB API configuration      
tmdb:
  api-url: https://api.themoviedb.org/3
  access-token: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkYzEzOThhZDciMTY4ZjM2ZGJkMGIzYTZmYTYzOThhYSIsIm5iZiI6MTc0OTkzNDEyNi4xNDgsInN1YiI6IjY4NGRlMDJlYzgzZWJlNzgxOWJiNGU1YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.oI0cWBV3BQmfGNqjh27YLAqNuZK2gIQW-wkYeamNv5Y"

# Logging configuration
logging:
  pattern:
    console: ""
  level:
    root: INFO
    org.shark.melian: DEBUG